In [1]:
import pandas as pd

C:\Users\Mohd Qausain\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
df=pd.read_csv('bhopal_crop_profit_data.csv')

In [ ]:
#  Output:  Revenue_per_acre,Profit_per_acre

In [10]:
df=df.drop(columns=['Year','Location','Season','Irrigation_Type'])

In [13]:
df=df[['Crop','Soil_Type','Area_acre','Season_Rainfall_mm','Total_Cost_per_acre','Revenue_per_acre','Profit_per_acre']]

In [19]:
df=df.drop(columns='Soil_Type')

In [24]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
df[]

,Crop,Area_acre,Season_Rainfall_mm,Total_Cost_per_acre,Revenue_per_acre,Profit_per_acre
0,Barley,9.7,48.0,13583,18591,5008
1,Barley,6.5,20.0,14548,23026,8478
2,Barley,10.3,36.0,14635,23600,8965
3,Barley,2.7,21.0,14631,19469,4838
4,Barley,11.6,77.0,15876,23588,7712
...,...,...,...,...,...,...
1645,Wheat,2.6,59.0,23817,41784,17967
1646,Wheat,2.3,39.0,26494,43766,17271
1647,Wheat,1.2,58.0,27747,44681,16933
1648,Wheat,11.6,29.0,25806,39882,14076
1649,Wheat,4.7,88.0,28572,33621,5049

In [36]:
ohe=OneHotEncoder(sparse_output=False)
x_encoded=ohe.fit_transform(df[['Crop']])

In [41]:
crop_columns=[
    '_'.join(map(str, col)) if isinstance(col, tuple) else str(col)
    for col in bad.columns
]

In [43]:
final_x=pd.DataFrame(x_encoded,columns=crop_columns)

In [47]:
final_df=pd.concat((df,final_x),axis=1)

In [53]:
final_df=final_df.drop(columns='Crop')

In [55]:
x=final_df.drop(columns=['Total_Cost_per_acre','Revenue_per_acre','Profit_per_acre'])

In [57]:
y=df[['Total_Cost_per_acre','Revenue_per_acre','Profit_per_acre']]

In [58]:
y

      Total_Cost_per_acre  Revenue_per_acre  Profit_per_acre
0                   13583             18591             5008
1                   14548             23026             8478
2                   14635             23600             8965
3                   14631             19469             4838
4                   15876             23588             7712
...                   ...               ...              ...
1645                23817             41784            17967
1646                26494             43766            17271
1647                27747             44681            16933
1648                25806             39882            14076
1649                28572             33621             5049

[1650 rows x 3 columns]

In [56]:
final_df

,Area_acre,Season_Rainfall_mm,Total_Cost_per_acre,Revenue_per_acre,Profit_per_acre,Barley,Cotton,Ground Nuts,Maize,Millets,Oil seeds,Paddy,Pulses,Sugarcane,Tobacco,Wheat
0,9.7,48.0,13583,18591,5008,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,6.5,20.0,14548,23026,8478,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,10.3,36.0,14635,23600,8965,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2.7,21.0,14631,19469,4838,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,11.6,77.0,15876,23588,7712,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1645,2.6,59.0,23817,41784,17967,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1646,2.3,39.0,26494,43766,17271,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1647,1.2,58.0,27747,44681,16933,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1648,11.6,29.0,25806,39882,14076,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1649,4.7,88.0,28572,33621,5049,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [59]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=.8,random_state=32)

In [69]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import accuracy_score
dt=DecisionTreeRegressor()
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)

In [100]:
y_test.iloc[4,:]

Total_Cost_per_acre    24667
Revenue_per_acre       31407
Profit_per_acre         6740
Name: 589, dtype: int64

In [99]:
y_pred[4]

array([17556, 20659,  3103])

In [101]:
import pickle

In [102]:
pickle.dump(dt,open('DescisionTreeRegressor.pkl','wb'))

In [103]:
pickle.dump(ohe,open('OneHotEncoder.pkl','wb'))