In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('data_core.csv')

In [ ]:
# Temperature Analysis:
df['Temparature'].describe()

count    8000.000000
mean       30.338895
std         4.478262
min        20.000000
25%        27.050000
50%        30.240000
75%        33.460000
max        40.000000
Name: Temparature, dtype: float64

In [ ]:
# Humidity
df['Humidity'].describe()

count    8000.000000
mean       59.210731
std         8.177366
min        40.020000
25%        53.277500
50%        59.110000
75%        65.082500
max        80.000000
Name: Humidity, dtype: float64

In [ ]:
df.describe()

,Temparature,Humidity,Moisture,Nitrogen,Potassium,Phosphorous
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,30.338895,59.210731,43.580862,18.429125,3.916375,18.512500
std,4.478262,8.177366,12.596156,11.852406,5.494807,13.244113
min,20.000000,40.020000,20.000000,0.000000,0.000000,0.000000
25%,27.050000,53.277500,33.967500,9.000000,0.000000,8.000000
50%,30.240000,59.110000,42.250000,14.000000,1.000000,18.000000
75%,33.460000,65.082500,52.950000,26.000000,5.000000,30.000000
max,40.000000,80.000000,70.000000,46.000000,23.000000,46.000000

In [ ]:
import plotly.express as px
import matplotlib.pyplot as plt

In [ ]:
df['Temparature']

0       26.00
1       29.00
2       34.00
3       32.00
4       28.00
        ...
7995    35.30
7996    39.39
7997    35.79
7998    37.78
7999    31.38
Name: Temparature, Length: 8000, dtype: float64

In [ ]:
df['Soil Type'].value_counts()

Soil Type
Clayey    1623
Black     1613
Red       1594
Loamy     1590
Sandy     1580
Name: count, dtype: int64

In [ ]:
df['Crop Type'].value_counts()

Crop Type
Sugarcane      763
Maize          753
Wheat          747
Ground Nuts    732
Pulses         728
Cotton         722
Millets        718
Tobacco        717
Oil seeds      711
Paddy          706
Barley         703
Name: count, dtype: int64

In [ ]:
df.columns

Index(['Temparature', 'Humidity', 'Moisture', 'Soil Type', 'Crop Type',
       'Nitrogen', 'Potassium', 'Phosphorous', 'Fertilizer Name'],
      dtype='str')

In [ ]:
df.drop(columns='Fertilizer Name',inplace=True)

In [ ]:
df['Crop Type2']=df['Crop Type']

In [ ]:
df.drop(columns='Crop Type',inplace  =True)

In [ ]:
df.rename(columns={'Crop Type2':'CropType'},inplace=True)

In [ ]:
df.head(2)

,Temparature,Humidity,Moisture,Soil Type,Nitrogen,Potassium,Phosphorous,CropType
0,26.0,52.0,38.0,Sandy,37,0,0,Maize
1,29.0,52.0,45.0,Loamy,12,0,36,Sugarcane

In [ ]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
df['CropType']=le1.fit_transform(df['CropType'])

In [ ]:
le2=LabelEncoder()
df['Soil Type']=le2.fit_transform(df['Soil Type'])

In [ ]:
le1.classes_

array(['Barley', 'Cotton', 'Ground Nuts', 'Maize', 'Millets', 'Oil seeds',
       'Paddy', 'Pulses', 'Sugarcane', 'Tobacco', 'Wheat'], dtype=object)

In [ ]:
le2.classes_

array(['Black', 'Clayey', 'Loamy', 'Red', 'Sandy'], dtype=object)

In [ ]:
df

,Temparature,Humidity,Moisture,Soil Type,Nitrogen,Potassium,Phosphorous,CropType
0,26.00,52.00,38.00,4,37,0,0,3
1,29.00,52.00,45.00,2,12,0,36,8
2,34.00,65.00,62.00,0,7,9,30,1
3,32.00,62.00,34.00,3,22,0,20,9
4,28.00,54.00,46.00,1,35,0,0,6
...,...,...,...,...,...,...,...,...
7995,35.30,59.61,44.25,2,10,14,10,5
7996,39.39,71.67,49.34,0,35,0,0,0
7997,35.79,67.64,45.04,3,41,0,0,0
7998,37.78,73.38,36.03,0,10,3,30,9
7999,31.38,48.73,62.27,2,11,2,33,4

In [ ]:
# Output is Crop Type:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
svm=SVC(kernel='sigmoid')
lr=LogisticRegression()
knn=KNeighborsClassifier(n_neighbors=9)
dtf=DecisionTreeClassifier()

In [ ]:
models_clf={
    'SVM':svm,
    'LogisticRegression':lr,
    'KNN':knn,
    'DTF':dtf
}

In [ ]:
models_clf.items()

dict_items([('SVM', SVC(kernel='sigmoid')), ('LogisticRegression', LogisticRegression()), ('KNN', KNeighborsClassifier())])

In [ ]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [ ]:
df

,Temparature,Humidity,Moisture,Soil Type,Nitrogen,Potassium,Phosphorous,CropType
0,26.00,52.00,38.00,4,37,0,0,3
1,29.00,52.00,45.00,2,12,0,36,8
2,34.00,65.00,62.00,0,7,9,30,1
3,32.00,62.00,34.00,3,22,0,20,9
4,28.00,54.00,46.00,1,35,0,0,6
...,...,...,...,...,...,...,...,...
7995,35.30,59.61,44.25,2,10,14,10,5
7996,39.39,71.67,49.34,0,35,0,0,0
7997,35.79,67.64,45.04,3,41,0,0,0
7998,37.78,73.38,36.03,0,10,3,30,9
7999,31.38,48.73,62.27,2,11,2,33,4

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=32,shuffle=True)

In [ ]:
def train_model(model,x_train,y_train,x_test,y_test):
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    return accuracy_score(y_pred=y_pred,y_true=y_test)

In [ ]:
accuracy_score_list

[0.098125, 0.093125, 0.100625, 0.090625]

In [ ]:
accuracy_score_list=[]

for name,real_model in  models_clf.items():
    acc=train_model(real_model,x_train,y_train,x_test,y_test)
    accuracy_score_list.append(acc)

LogisticRegression()

In [ ]:
from sklearn.model_selection import GridSearchCV,KFold

In [ ]:
KNeighborsClassifier

sklearn.neighbors._classification.KNeighborsClassifier

In [ ]:
kfold=KFold(n_splits=5,shuffle=True,random_state=32)

In [ ]:
n_params={
    'n_neighbors':[2,3,4,5,6,7,8,9,10],
    'algorithm':['ball_tree', 'kd_tree', 'brute'],
    
    }

In [ ]:
gcv=GridSearchCV(estimator=knn,param_grid=n_params,scoring='r2',cv=kfold,verbose=2)

In [ ]:
df

,Temparature,Humidity,Moisture,Soil Type,Nitrogen,Potassium,Phosphorous,CropType
0,26.00,52.00,38.00,4,37,0,0,3
1,29.00,52.00,45.00,2,12,0,36,8
2,34.00,65.00,62.00,0,7,9,30,1
3,32.00,62.00,34.00,3,22,0,20,9
4,28.00,54.00,46.00,1,35,0,0,6
...,...,...,...,...,...,...,...,...
7995,35.30,59.61,44.25,2,10,14,10,5
7996,39.39,71.67,49.34,0,35,0,0,0
7997,35.79,67.64,45.04,3,41,0,0,0
7998,37.78,73.38,36.03,0,10,3,30,9
7999,31.38,48.73,62.27,2,11,2,33,4

In [ ]:
gcv.fit(x_train,y_train)

Fitting 5 folds for each of 27 candidates, totalling 135 fits
[CV] END .................algorithm=ball_tree, n_neighbors=2; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=2; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=2; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=2; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=2; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=3; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=3; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=3; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=3; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=3; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=4; total time=   0.1s
[CV] END .................algorithm=ball_tree, n_neighbors=4; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=4; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=4; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=4; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=5; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=5; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=5; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=5; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=5; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=6; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=6; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=6; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=6; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=6; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=7; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=7; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=7; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=7; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=7; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=8; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=8; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=8; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=8; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=8; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=9; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=9; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=9; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=9; total time=   0.0s
[CV] END .................algorithm=ball_tree, n_neighbors=9; total time=   0.0s
[CV] END ................algorithm=ball_tree, n_neighbors=10; total time=   0.0s
[CV] END ................algorithm=ball_tree, n_neighbors=10; total time=   0.0s
[CV] END ................algorithm=ball_tree, n_neighbors=10; total time=   0.0s
[CV] END ................algorithm=ball_tree, n_neighbors=10; total time=   0.0s
[CV] END ................algorithm=ball_tree, n_neighbors=10; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=2; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=2; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=2; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=2; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=2; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=3; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=3; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=3; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=3; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=3; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=4; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=4; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=4; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=4; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=4; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=5; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=5; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=5; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=5; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=5; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=6; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=6; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=6; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=6; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=6; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=7; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=7; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=7; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=7; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=7; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=8; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=8; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=8; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=8; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=8; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=9; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=9; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=9; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=9; total time=   0.0s
[CV] END ...................algorithm=kd_tree, n_neighbors=9; total time=   0.0s
[CV] END ..................algorithm=kd_tree, n_neighbors=10; total time=   0.0s
[CV] END ..................algorithm=kd_tree, n_neighbors=10; total time=   0.0s
[CV] END ..................algorithm=kd_tree, n_neighbors=10; total time=   0.0s
[CV] END ..................algorithm=kd_tree, n_neighbors=10; total time=   0.0s
[CV] END ..................algorithm=kd_tree, n_neighbors=10; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=2; total time=   3.3s
[CV] END .....................algorithm=brute, n_neighbors=2; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=2; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=2; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=2; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=3; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=3; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=3; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=3; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=3; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=4; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=4; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=4; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=4; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=4; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=5; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=5; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=5; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=5; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=5; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=6; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=6; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=6; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=6; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=6; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=7; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=7; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=7; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=7; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=7; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=8; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=8; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=8; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=8; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=8; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=9; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=9; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=9; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=9; total time=   0.0s
[CV] END .....................algorithm=brute, n_neighbors=9; total time=   0.0s
[CV] END ....................algorithm=brute, n_neighbors=10; total time=   0.0s
[CV] END ....................algorithm=brute, n_neighbors=10; total time=   0.0s
[CV] END ....................algorithm=brute, n_neighbors=10; total time=   0.0s
[CV] END ....................algorithm=brute, n_neighbors=10; total time=   0.0s
[CV] END ....................algorithm=brute, n_neighbors=10; total time=   0.0s

GridSearchCV(cv=KFold(n_splits=5, random_state=32, shuffle=True),
             estimator=KNeighborsClassifier(n_neighbors=9),
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9, 10]},
             scoring='r2', verbose=2)

In [ ]:
gcv.best_score_

np.float64(-0.9620032775700939)

In [ ]:
pd.DataFrame(gcv.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_penalty,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004986,0.000991,0.000000,0.000000,l1,lbfgs,"{'penalty': 'l1', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
1,0.012092,0.003332,0.000000,0.000000,l1,liblinear,"{'penalty': 'l1', 'solver': 'liblinear'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
2,0.003107,0.000840,0.000000,0.000000,l1,newton-cg,"{'penalty': 'l1', 'solver': 'newton-cg'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
3,0.461172,0.061392,0.008815,0.005436,l2,lbfgs,"{'penalty': 'l2', 'solver': 'lbfgs'}",-0.925486,-1.238934,-1.327616,-1.185078,-1.149016,-1.165226,0.134116,1
4,0.007999,0.001082,0.000000,0.000000,l2,liblinear,"{'penalty': 'l2', 'solver': 'liblinear'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
5,0.469759,0.076538,0.006942,0.001445,l2,newton-cg,"{'penalty': 'l2', 'solver': 'newton-cg'}",-0.924647,-1.271984,-1.399040,-1.116610,-1.176508,-1.177758,0.158525,2
6,0.003107,0.000990,0.000000,0.000000,elasticnet,lbfgs,"{'penalty': 'elasticnet', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
7,0.003581,0.000310,0.000000,0.000000,elasticnet,liblinear,"{'penalty': 'elasticnet', 'solver': 'liblinear'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
8,0.003309,0.001316,0.000000,0.000000,elasticnet,newton-cg,"{'penalty': 'elasticnet', 'solver': 'newton-cg'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3

In [ ]:
from mlxtend.feature_selection import SequentialFeatureSelector
sfs=SequentialFeatureSelector(estimator=knn,k_features='best',forward=False,verbose=2,cv=kfold,scoring='accuracy')
sfs.fit(x_train,y_train)

[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:    1.5s finished

[2026-09-26 16:56:46] Features: 6/1 -- score: 0.09765625[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    1.5s finished

[2026-09-26 16:56:48] Features: 5/1 -- score: 0.1015625[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.8s finished

[2026-09-26 16:56:49] Features: 4/1 -- score: 0.099375[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.5s finished

[2026-09-26 16:56:50] Features: 3/1 -- score: 0.09953125[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.4s finished

[2026-09-26 16:56:50] Features: 2/1 -- score: 0.09906249999999998[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.1s finished

[2026-09-26 16:56:50] Features: 1/1 -- score: 0.09921875

SequentialFeatureSelector(cv=KFold(n_splits=5, random_state=32, shuffle=True),
                          estimator=KNeighborsClassifier(n_neighbors=9),
                          forward=False, k_features=(1, 7), scoring='accuracy',
                          verbose=2)

In [ ]:
bes_feature=

In [ ]:
x_train=sfs.transform(x_train)

In [ ]:
col=x_train.columns

In [ ]:
x_test=sfs.transform(x_test)
x_test=pd.DataFrame(x_test,columns=col[[0, 1, 2, 3, 6]])

In [ ]:
x_train=pd.DataFrame(x_train,columns=col[[0, 1, 2, 3, 6]])

In [ ]:
x_train

      Temparature  Humidity  Moisture  Soil Type  Phosphorous
0           33.79     70.29     36.68        0.0         22.0
1           31.64     68.37     49.45        0.0          0.0
2           30.14     55.49     45.37        1.0          0.0
3           25.88     63.35     70.00        0.0         36.0
4           32.44     75.96     56.23        4.0         35.0
...           ...       ...       ...        ...          ...
6395        25.23     48.90     32.37        1.0          1.0
6396        30.18     72.18     46.54        2.0          0.0
6397        37.05     66.11     38.47        0.0         28.0
6398        26.74     51.72     49.96        2.0         21.0
6399        35.86     71.33     44.81        4.0          2.0

[6400 rows x 5 columns]

In [ ]:
subset=pd.DataFrame(sfs.subsets_).T

In [ ]:
subset.sort_values('avg_score',ascending=False)

,feature_idx,cv_scores,avg_score,feature_names
5,"(0, 1, 2, 3, 6)","[0.10546875, 0.09375, 0.103125, 0.1015625, 0.1...",0.101562,"(Temparature, Humidity, Moisture, Soil Type, P..."
3,"(0, 1, 2)","[0.0984375, 0.1109375, 0.103125, 0.08671875, 0...",0.099531,"(Temparature, Humidity, Moisture)"
4,"(0, 1, 2, 3)","[0.1109375, 0.1015625, 0.09921875, 0.090625, 0...",0.099375,"(Temparature, Humidity, Moisture, Soil Type)"
1,"(1,)","[0.09453125, 0.10078125, 0.10546875, 0.1078125...",0.099219,"(Humidity,)"
2,"(0, 1)","[0.096875, 0.09453125, 0.11171875, 0.09609375,...",0.099062,"(Temparature, Humidity)"
6,"(0, 1, 2, 3, 5, 6)","[0.11015625, 0.0953125, 0.08671875, 0.090625, ...",0.097656,"(Temparature, Humidity, Moisture, Soil Type, P..."
7,"(0, 1, 2, 3, 4, 5, 6)","[0.09375, 0.09609375, 0.0890625, 0.08984375, 0...",0.094531,"(Temparature, Humidity, Moisture, Soil Type, N..."

In [ ]:
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
print(accuracy_score(y_pred=y_pred,y_true=y_test))

0.086875

In [ ]:
y_pred=knn.predict(x_test)

In [ ]:
x_train.columns

Index(['Temparature', 'Humidity', 'Moisture', 'Soil Type', 'Phosphorous'], dtype='str')

In [ ]:
import pickle
pickle.dump(knn,open('KNN.pkl','wb'))